general:
  formMode: 'BS3'
  holdOn: false
  holdOnOptions: "HoldOnOptions"
  requiredIndicator: 2


forms:
  example_group:
    namespace: "\\Example\\Vendor\\Namespace"
    directory: "dir/from/project/root"


debugging:
  enabled: false
  userCheckMethod: "\\Example\\Vendor\\Object::isFormConfigDebugger"


csrf:
  enabled: false
  tokenNameMethod: "\\Example\\Vendor\\Object::getCSRFTokenName"
  tokenValueMethod: "\\Example\\Vendor\\Object::getCSRFTokenValue"
  tokenValidationMethod: "\\Example\\Vendor\\Object::validateToken"
